In [1]:
import numpy as np
from pyspark.mllib.clustering import KMeans

In [2]:
from pyspark import  SparkContext
sc = SparkContext( 'local', 'pyspark')

In [3]:
iris = sc.textFile("irisdata.csv")

In [4]:
iris.count()

150

In [5]:
iris.take(5)

['5.1,3.5,1.4,0.2,Iris-setosa',
 '4.9,3,1.4,0.2,Iris-setosa',
 '4.7,3.2,1.3,0.2,Iris-setosa',
 '4.6,3.1,1.5,0.2,Iris-setosa',
 '5,3.6,1.4,0.2,Iris-setosa']

In [6]:
def parseData(line):
    lsplit = line.split(",") 
    return np.array([float(lsplit[0]),float(lsplit[1]), float(lsplit[2]),float(lsplit[3])])

In [11]:
inputt = iris.map(parseData)

In [12]:
inputt.count()

150

In [13]:
inputt.take(5)

[array([ 5.1,  3.5,  1.4,  0.2]),
 array([ 4.9,  3. ,  1.4,  0.2]),
 array([ 4.7,  3.2,  1.3,  0.2]),
 array([ 4.6,  3.1,  1.5,  0.2]),
 array([ 5. ,  3.6,  1.4,  0.2])]

In [10]:
nclust = 3

In [14]:
model = KMeans.train(inputt, nclust)

In [15]:
print("Final centers: " + str(model.clusterCenters))
print("Total Cost: " + str(model.computeCost(inputt)))

Final centers: [array([ 5.006,  3.418,  1.464,  0.244]), array([ 5.9016129 ,  2.7483871 ,  4.39354839,  1.43387097]), array([ 6.85      ,  3.07368421,  5.74210526,  2.07105263])]
Total Cost: 78.94084142614648


In [16]:
def parseData2(line):
    ld = line.split(",") 
    return (ld[4],np.array([float(ld[0]),float(ld[1]), float(ld[2]),float(ld[3])]))

In [18]:
checkData = iris.map(parseData2)

In [19]:
checkData.count()

150

In [20]:
checkData.take(5)

[('Iris-setosa', array([ 5.1,  3.5,  1.4,  0.2])),
 ('Iris-setosa', array([ 4.9,  3. ,  1.4,  0.2])),
 ('Iris-setosa', array([ 4.7,  3.2,  1.3,  0.2])),
 ('Iris-setosa', array([ 4.6,  3.1,  1.5,  0.2])),
 ('Iris-setosa', array([ 5. ,  3.6,  1.4,  0.2]))]

In [24]:
labelsAndPreds = checkData.map(lambda p: (p[0], model.predict(p[1])) )

In [26]:
labelsAndPreds.saveAsTextFile("Kmeans_spark")