In [1]:
my_list = [1,2,3]

In [2]:
my_list

[1, 2, 3]

In [3]:
import numpy as np

In [5]:
arr = np.array(my_list)

In [6]:
arr

array([1, 2, 3])

In [7]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [8]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [12]:
lin = np.linspace(0, 25, 10)

In [15]:
lin = lin.reshape(5,2)

In [16]:
lin

array([[  0.        ,   2.77777778],
       [  5.55555556,   8.33333333],
       [ 11.11111111,  13.88888889],
       [ 16.66666667,  19.44444444],
       [ 22.22222222,  25.        ]])

In [18]:
np.zeros((3,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [19]:
np.ones((4,4))

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [20]:
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [38]:
n = np.random.rand(10)

In [40]:
n

array([ 0.52840357,  0.01658915,  0.86035887,  0.58100367,  0.82708533,
        0.53065111,  0.15706159,  0.06950401,  0.87870894,  0.55839981])

In [39]:
n1 = np.random.randn(10)

In [41]:
n1

array([  4.41060762e-04,   6.25124539e-01,   4.44555087e-01,
        -1.83865753e+00,   9.96021653e-01,  -1.94882590e+00,
         5.04559944e-01,  -8.92820859e-01,   9.85992501e-01,
        -1.12769583e+00])

In [25]:
ranarr = np.random.randint(1, 10, 20)

In [27]:
ranarr.shape

(20,)

In [28]:
ranarr = ranarr.reshape(5,4)

In [29]:
ranarr

array([[2, 2, 4, 2],
       [2, 4, 2, 9],
       [3, 1, 2, 1],
       [5, 1, 9, 6],
       [9, 2, 5, 7]])

In [30]:
num = np.random.randint(1,80,20)

In [31]:
num

array([47, 51, 37, 52, 30, 36, 11, 34, 39, 51, 76,  7, 43, 73, 45, 10, 47,
       75, 49, 38])

In [32]:
num.max()

76

In [33]:
num.min()

7

In [34]:
num.argmax()

10

In [35]:
num.argmin()

11

In [36]:
ranarr.dtype

dtype('int64')

In [37]:
num.dtype

dtype('int64')

In [43]:
n.dtype

dtype('float64')

In [44]:
n1.dtype

dtype('float64')

In [48]:
from numpy.random import randint

In [49]:
randint(2,10)

5

In [50]:
arr = np.arange(0, 11)

In [51]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [52]:
arr[8]

8

In [53]:
arr[1:5]

array([1, 2, 3, 4])

In [54]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [55]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [56]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [57]:
arr[0:5] = 100

In [58]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [59]:
arr = np.arange(0, 11)

In [60]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [61]:
slice_of_arr = arr[0:6]

In [62]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [63]:
slice_of_arr[:] = 99

In [64]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [65]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [66]:
arr_copy = arr.copy()

In [67]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [68]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [69]:
arr_copy[:] = 100

In [70]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [71]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [73]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [74]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [75]:
arr_2d[0][0]

5

In [76]:
arr_2d[0]

array([ 5, 10, 15])

In [77]:
arr_2d[1][1]

25

In [78]:
arr_2d[2,1]

40

In [79]:
arr_2d[2][1]

40

In [80]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [81]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [83]:
arr_2d[1:,:]

array([[20, 25, 30],
       [35, 40, 45]])

In [85]:
arr_2d[:,1:]

array([[10, 15],
       [25, 30],
       [40, 45]])

In [86]:
arr = np.arange(1,11)

In [87]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [89]:
bool_arr = arr > 5

In [90]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,  True], dtype=bool)

In [91]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [92]:
arr[arr > 5]

array([ 6,  7,  8,  9, 10])

In [93]:
arr[arr < 3]

array([1, 2])

In [94]:
arr_2d = np.arange(50).reshape(5, 10)

In [95]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [96]:
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])

In [97]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [98]:
arr + arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [99]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [100]:
arr * arr

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [101]:
arr + 100

array([101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [102]:
arr * 10

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [103]:
arr - 10

array([-9, -8, -7, -6, -5, -4, -3, -2, -1,  0])

In [105]:
arr = np.arange(0, 11)

In [106]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [107]:
arr / arr

/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([ nan,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.])

In [108]:
1 / arr

/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([        inf,  1.        ,  0.5       ,  0.33333333,  0.25      ,
        0.2       ,  0.16666667,  0.14285714,  0.125     ,  0.11111111,
        0.1       ])

In [109]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [110]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [111]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

In [112]:
np.max(arr)

10

In [113]:
arr.max()

10

In [114]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [116]:
np.log(arr)

/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([       -inf,  0.        ,  0.69314718,  1.09861229,  1.38629436,
        1.60943791,  1.79175947,  1.94591015,  2.07944154,  2.19722458,
        2.30258509])

Numpy Exercise

In [117]:
import numpy as np

In [118]:
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [119]:
np.ones(10)

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [122]:
five = [5,5,5,5,5,5,5,5,5,5]
np.array(five)

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [123]:
np.ones(10) * 5

array([ 5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.])

In [126]:
np.arange(10, 51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [127]:
np.arange(10, 51, 2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [128]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [129]:
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [137]:
np.random.rand(1)

array([ 0.11683839])

In [138]:
np.random.randn(25)

array([-0.50762015, -0.19219674,  0.25026973, -1.46323401,  1.28570683,
       -0.28538715,  1.80642298, -0.3124495 , -0.11269431,  0.69403224,
        0.92504715, -2.32103251, -0.73914302, -1.13320316, -0.70194416,
        0.12037208,  0.65969742, -0.0869008 , -1.57446087,  0.97335896,
        0.18252676,  0.08893144, -0.24189277,  1.03655306, -0.30710515])

In [142]:
np.arange(0.01, 1.01, 0.01).reshape(10,10)

array([[ 0.01,  0.02,  0.03,  0.04,  0.05,  0.06,  0.07,  0.08,  0.09,  0.1 ],
       [ 0.11,  0.12,  0.13,  0.14,  0.15,  0.16,  0.17,  0.18,  0.19,  0.2 ],
       [ 0.21,  0.22,  0.23,  0.24,  0.25,  0.26,  0.27,  0.28,  0.29,  0.3 ],
       [ 0.31,  0.32,  0.33,  0.34,  0.35,  0.36,  0.37,  0.38,  0.39,  0.4 ],
       [ 0.41,  0.42,  0.43,  0.44,  0.45,  0.46,  0.47,  0.48,  0.49,  0.5 ],
       [ 0.51,  0.52,  0.53,  0.54,  0.55,  0.56,  0.57,  0.58,  0.59,  0.6 ],
       [ 0.61,  0.62,  0.63,  0.64,  0.65,  0.66,  0.67,  0.68,  0.69,  0.7 ],
       [ 0.71,  0.72,  0.73,  0.74,  0.75,  0.76,  0.77,  0.78,  0.79,  0.8 ],
       [ 0.81,  0.82,  0.83,  0.84,  0.85,  0.86,  0.87,  0.88,  0.89,  0.9 ],
       [ 0.91,  0.92,  0.93,  0.94,  0.95,  0.96,  0.97,  0.98,  0.99,  1.  ]])

In [144]:
np.linspace(0, 1, 20)

array([ 0.        ,  0.05263158,  0.10526316,  0.15789474,  0.21052632,
        0.26315789,  0.31578947,  0.36842105,  0.42105263,  0.47368421,
        0.52631579,  0.57894737,  0.63157895,  0.68421053,  0.73684211,
        0.78947368,  0.84210526,  0.89473684,  0.94736842,  1.        ])

In [145]:
mat = np.arange(1, 26).reshape(5,5)

In [146]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [147]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [148]:
mat[3,4]

20

In [154]:
mat[0:3, 1:2]

array([[ 2],
       [ 7],
       [12]])

In [156]:
mat[4]

array([21, 22, 23, 24, 25])

In [157]:
mat[3:,0:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [158]:
mat.sum()

325

In [160]:
mat.std()

7.2111025509279782

In [165]:
mat.sum(axis = 0)

array([55, 60, 65, 70, 75])